import test from 'node:test';import assert from 'node:assert/strict';import express from 'express';import {DatabaseSync} from 'node:sqlite';import {randomUUID} from 'node:crypto';import {installPlatform,controlSignature} from '../server/platform.js';
test('Paso signed administration: separate plans, coupons, subscriptions, payments, audit and existing stores',async t=>{
 const key='synthetic-paso-control-secret-32-characters';const old=process.env.PASO_CONTROL_SECRET;process.env.PASO_CONTROL_SECRET=key;t.after(()=>{if(old)process.env.PASO_CONTROL_SECRET=old;else delete process.env.PASO_CONTROL_SECRET});
 const db=new DatabaseSync(':memory:');db.exec('CREATE TABLE tenants(id TEXT PRIMARY KEY,data TEXT NOT NULL); CREATE TABLE users(id TEXT PRIMARY KEY,email TEXT UNIQUE,password TEXT,salt TEXT); CREATE TABLE memberships(user_id TEXT,tenant_id TEXT,PRIMARY KEY(user_id,tenant_id));');
 const app=express();app.use(express.json({verify:(req,res,b)=>req.rawBody=b.toString()}));installPlatform(app,db);app.use((err,req,res,next)=>res.status(400).json({error:'Invalid synthetic request'}));const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));t.after(()=>{server.close();db.close()});
 const request=async(path,method='GET',data,valid=true)=>{const body=data?JSON.stringify(data):'',ts=String(Date.now()),nonce=randomUUID(),actor='synthetic-superadmin',url='/api/control/'+path;const r=await fetch('http://127.0.0.1:'+server.address().port+url,{method,headers:{'content-type':'application/json','x-paso-timestamp':ts,'x-paso-nonce':nonce,'x-paso-actor':actor,'x-paso-signature':valid?controlSignature(key,method,url,ts,nonce,actor,body):'0'.repeat(64)},...(body?{body}:{})});return {status:r.status,data:await r.json()}};
 assert.equal((await request('plans','GET',undefined,false)).status,401);
 const created=await request('tenants','POST',{name:'Tienda ficticia',slug:'demo-test',email:'fiction@example.test',password:'synthetic-password',expires_at:'2026-12-01T00:00:00Z'});assert.equal(created.status,201,JSON.stringify(created));const id=created.data.id;
 const fields={code:'premium',name:'Plan Paso',description:'Prueba',price:300000,currency:'ARS',billing_interval:'month',trial_days:14,active:true};const p=await request('plans','POST',fields);assert.equal(p.status,200);
 assert.equal((await request('tenants/'+id+'/subscription','PUT',{plan_id:p.data.id})).status,200);
 assert.equal((await request('tenants/'+id+'/subscription')).data.subscription.contracted_price,300000);
 assert.equal((await request('plans/'+p.data.id,'PUT',{...fields,price:400000})).status,200);assert.equal((await request('tenants/'+id+'/subscription')).data.subscription.contracted_price,300000);
 const c={code:'PASO10',description:'Beneficio',kind:'percent',value:1000,currency:'ARS',starts_at:'2020-01-01T00:00:00Z',ends_at:null,max_uses:10,max_per_tenant:1,benefit_months:1,active:true,plan_ids:[p.data.id]};assert.equal((await request('coupons','POST',c)).status,200);assert.equal((await request('tenants/'+id+'/coupon','POST',{code:'PASO10'})).status,200);assert.equal((await request('tenants/'+id+'/coupon','POST',{code:'PASO10'})).status,409);
 const payment={payment_id:'synthetic-payment',amount:300000,contracted_price:300000,currency:'ARS',billing_interval:'month',plan_id:p.data.id,paid_at:'2026-10-04T12:00:00Z'};
 const first=await request('tenants/'+id+'/payment','POST',payment);assert.equal(first.status,200);assert.equal(first.data.period_end,'2027-01-01T00:00:00.000Z');assert.deepEqual((await request('tenants/'+id+'/payment','POST',payment)).data,first.data);
 assert.equal((await request('tenants/'+id+'/payment','POST',{...payment,payment_id:'bad',amount:1})).status,409);
 const dashboard=await request('dashboard');assert.equal(dashboard.data.total,1);assert.equal(dashboard.data.plans[0].count,1);assert.equal((await request('audit')).data.filter(x=>x.action==='subscription.payment').length,1);
 assert.equal(db.prepare('SELECT count(*) n FROM tenants').get().n,1);assert.equal(db.prepare('SELECT count(*) n FROM control_payments').get().n,1);
});
